// components/RiskImage.jsx
"use client";
import { Image as ImageIcon } from "lucide-react";

export default function RiskImage({ image }) {
  if (!image) return null;

  return (
    <div className="bg-zinc-950/60 border border-emerald-900/40 rounded-3xl p-8">
      <div className="flex items-center gap-3 mb-6">
        <ImageIcon className="text-purple-400" size={28} />
        <h3 className="text-2xl font-semibold">Full AI Risk Map</h3>
      </div>
      
      <div className="flex justify-center bg-black/80 rounded-2xl p-6 border border-zinc-800">
        <img
          src={`http://127.0.0.1:8000/maps/${image}`}
          alt="Risk Map"
          className="rounded-2xl shadow-2xl max-h-[620px] border border-emerald-900/30"
        />
      </div>
      
      <p className="text-center text-xs text-zinc-500 mt-4">
        Generated by AI Model • Viridis Color Scale
      </p>
    </div>
  );
}